/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterComp: typeof import('./src/components/Main/FooterComp.vue')['default']
    HeaderComp: typeof import('./src/components/Main/HeaderComp.vue')['default']
    HomeComp: typeof import('./src/components/Home/HomeComp.vue')['default']
    LogComp: typeof import('./src/components/Log/LogComp.vue')['default']
    LoginComp: typeof import('./src/components/Login/LoginComp.vue')['default']
    MainComp: typeof import('./src/components/Main/MainComp.vue')['default']
    MiddleComp: typeof import('./src/components/Main/MiddleComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SigninComp: typeof import('./src/components/Login/SigninComp.vue')['default']
  }
}
